[package]
name = "c8e"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
minifb = "0.28.0"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
